### ISSUE TITLE
Looping in _get_response

### ISSUE THREAD

**Issue by kevsheb** [ulmusic/python-evolver#1]
DS_sweep loops to alter a variable and inspect the relationship on the contact angles. After some time the program will get stuck looping in _get_response (there doesn't seem to be a patter to when it loops). From what I can tell it's getting stuck during the E.open_file call.

**Comment by elmisback** [comment]
I'm getting an error after evolver tries to read "zebra.cmd". I'm assuming that's a separate file. Could you upload that file or modify DS_sweep so that it doesn't use zebra.cmd?

Edit: I just found zebra.cmd on your other repo. I'll try using that.

**Comment by elmisback** [comment]
The program was looking for the delimeter in each chunk it read, but not in the composite of the chunks, so eventually it failed to find a delimeter and broke. I fixed this along with open/close_file in evolver.py and was able to obtain a graph using DS_sweep, so I'm going to close this issue.
